# -*- coding: utf-8 -*-
"""DRL_Agent_Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ePdlBwof8jLTT5kRYLqgMKsnwCs5Pf3o
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile memory.py
# import random
# from collections import deque
# import numpy as np
# 
# class ReplayMemory:
#     def __init__(self, capacity):
#         self.buffer = deque(maxlen=capacity)
# 
#     def push(self, s, a, r, s2, d):
#         self.buffer.append((s, a, r, s2, d))
# 
#     def sample(self, batch_size):
#         batch = random.sample(self.buffer, batch_size)
#         s, a, r, s2, d = zip(*batch)
# 
#         return (
#             np.array(s, dtype=np.float32),
#             np.array(a, dtype=np.int64),
#             np.array(r, dtype=np.float32),
#             np.array(s2, dtype=np.float32),
#             np.array(d, dtype=np.float32),
#         )
# 
#     def __len__(self):
#         return len(self.buffer)
# 
# 
# class TraumaMemory(ReplayMemory):
#     def __init__(self, capacity):
#         super().__init__(capacity)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile abs_env.py
# import numpy as np
# 
# GRAVITY = 9.81
# DT = 0.01
# 
# VEHICLE_MASS = 1500
# WHEEL_RADIUS = 0.30
# P_MAX = 1e7
# 
# LAMBDA_OPT_MIN = 0.15
# LAMBDA_OPT_MAX = 0.25
# LAMBDA_LOCK = 0.80
# 
# ROAD_CONDITIONS = {
#     "dry": 1.0,
#     "wet": 0.7,
#     "snow": 0.4,
#     "ice": 0.2,
# }
# 
# 
# class Wheel:
#     def __init__(self):
#         self.omega = 0
#         self.pressure = 0
#         self.slip = 0
# 
#     def reset(self, v):
#         self.omega = v / WHEEL_RADIUS
#         self.pressure = 0
#         self.slip = 0
# 
#     def step(self, v, action):
# 
#         delta = {0: 0.0, 1: 2e5, 2: -2e5}[action]
#         self.pressure = np.clip(self.pressure + delta, 0, P_MAX)
# 
#         brake = self.pressure * 1e-6
#         self.omega = max(0.0, self.omega - brake)
# 
#         v_wheel = self.omega * WHEEL_RADIUS
# 
#         self.slip = abs(v - v_wheel) / max(v, 1e-3)
#         self.slip = np.clip(self.slip, 0, 1)
# 
#         return self.slip
# 
# 
# class ABSEnv:
# 
#     def __init__(self, mode="global", road="wet", max_steps=300):
#         self.mode = mode
#         self.road = road
#         self.max_steps = max_steps
# 
#         self.wheels = [Wheel() for _ in range(4)]
# 
#     def reset(self):
#         self.v = np.random.uniform(20, 30)
#         self.t = 0
# 
#         for w in self.wheels:
#             w.reset(self.v)
# 
#         return self._state(), {}
# 
#     def step(self, action):
# 
#         self.t += 1
# 
#         if self.mode == "global":
#             action = [action] * 4
# 
#         slips = [w.step(self.v, a) for w, a in zip(self.wheels, action)]
# 
#         mu = ROAD_CONDITIONS[self.road]
# 
#         force = sum(mu * (VEHICLE_MASS * GRAVITY / 4) for _ in slips)
# 
#         acc = force / VEHICLE_MASS
#         self.v = max(0, self.v - acc * DT)
# 
#         reward = 0.0
#         for s in slips:
#             if LAMBDA_OPT_MIN <= s <= LAMBDA_OPT_MAX:
#                 reward += 1.0
#             elif s > LAMBDA_LOCK:
#                 reward -= 2.0
#             else:
#                 reward -= abs(s - 0.2)
# 
#         reward = np.clip(reward, -5, 5)
# 
#         terminated = self.v < 0.1
#         truncated = self.t >= self.max_steps
# 
#         return self._state(), reward, terminated, truncated, {
#             "slips": slips,
#             "locked": any(s > LAMBDA_LOCK for s in slips)
#         }
# 
#     def _state(self):
#         s = [self.v / 50.0]
#         for w in self.wheels:
#             s += [w.slip, w.omega / 100, w.pressure / P_MAX]
#         return np.array(s, dtype=np.float32)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile agent_s1.py
# import random
# import numpy as np
# import torch
# import torch.nn as nn
# import torch.optim as optim
# import torch.nn.functional as F
# from memory import ReplayMemory
# 
# 
# class QNet(nn.Module):
#     def __init__(self):
#         super().__init__()
#         self.net = nn.Sequential(
#             nn.Linear(13, 256),
#             nn.ReLU(),
#             nn.Linear(256, 256),
#             nn.ReLU(),
#             nn.Linear(256, 128),
#             nn.ReLU(),
#             nn.Linear(128, 3)
#         )
# 
#     def forward(self, x):
#         return self.net(x)
# 
# 
# class DQNGlobalAgent:
# 
#     def __init__(self):
# 
#         self.q = QNet()
#         self.target = QNet()
#         self.target.load_state_dict(self.q.state_dict())
# 
#         self.opt = optim.Adam(self.q.parameters(), lr=5e-5)
# 
#         self.memory = ReplayMemory(100000)
# 
#         self.steps = 0
#         self.gamma = 0.99
# 
#     @property
#     def epsilon(self):
#         return max(0.05, np.exp(-self.steps / 8000))
# 
#     def act(self, s):
#         self.steps += 1
# 
#         if random.random() < self.epsilon:
#             return random.randint(0, 2)
# 
#         s = torch.tensor(s, dtype=torch.float32).unsqueeze(0)
#         return int(self.q(s).argmax(1))
# 
#     def store(self, s,a,r,s2,d, trauma=False):
#         self.memory.push(s,a,r,s2,d)
# 
#     def optimize(self):
# 
#         if len(self.memory) < 128:
#             return None
# 
#         s,a,r,s2,d = self.memory.sample(128)
# 
#         s = torch.tensor(s)
#         a = torch.tensor(a)
#         r = torch.tensor(r)
#         s2 = torch.tensor(s2)
#         d = torch.tensor(d)
# 
#         q = self.q(s).gather(1, a.unsqueeze(1)).squeeze()
# 
#         # 🔥 DOUBLE DQN STABLE
#         with torch.no_grad():
#             next_actions = self.q(s2).argmax(1)
#             q2 = self.target(s2).gather(1, next_actions.unsqueeze(1)).squeeze()
#             target = r + self.gamma * q2 * (1 - d)
# 
#         loss = F.smooth_l1_loss(q, target)
# 
#         self.opt.zero_grad()
#         loss.backward()
# 
#         torch.nn.utils.clip_grad_norm_(self.q.parameters(), 5.0)
# 
#         self.opt.step()
# 
#         # 🔥 slow target update (VERY IMPORTANT)
#         if self.steps % 1000 == 0:
#             self.target.load_state_dict(self.q.state_dict())
# 
#         return loss.item()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train.py
# 
# def train(agent, env, episodes=10):
# 
#     rewards = []
#     losses = []
#     slip_errors = []
# 
#     for ep in range(episodes):
# 
#         s, _ = env.reset()
# 
#         total = 0
#         ep_losses = []
#         ep_slip_error = []
# 
#         while True:
# 
#             a = agent.act(s)
# 
#             s2, r, terminated, truncated, info = env.step(a)
# 
#             done = terminated or truncated
# 
#             slips = info["slips"]
# 
#             slip_error = (
#                 sum(abs(x - 0.2) for x in slips)
#                 / len(slips)
#             )
# 
#             ep_slip_error.append(slip_error)
# 
#             agent.store(
#                 s,
#                 a,
#                 r,
#                 s2,
#                 done
#             )
# 
#             loss = agent.optimize()
# 
#             if loss is not None:
#                 ep_losses.append(loss)
# 
#             s = s2
#             total += r
# 
#             if done:
#                 break
# 
#         rewards.append(total)
# 
#         losses.append(
#             sum(ep_losses)/len(ep_losses)
#             if ep_losses else 0
#         )
# 
#         slip_errors.append(
#             sum(ep_slip_error)/len(ep_slip_error)
#         )
# 
#         print(
#             f"Episode {ep}: reward = {total:.2f}"
#         )
# 
#     return rewards, losses, slip_errors

from abs_env import ABSEnv
from agent_s1 import DQNGlobalAgent
from train import train

env = ABSEnv(mode="global", road="wet")
agent = DQNGlobalAgent()
rewards, losses, slip_errors = train(agent, env, episodes=200)

import matplotlib.pyplot as plt
import numpy as np

def plot_rewards(rewards):

    rewards = np.array(rewards)

    window = 10
    smooth = np.convolve(rewards, np.ones(window)/window, mode='valid')

    plt.figure()
    plt.plot(rewards, alpha=0.3, label="Raw Reward")
    plt.plot(range(window-1, len(rewards)), smooth, label="Smoothed Reward")
    plt.title("Cumulative Reward (Training Progress)")
    plt.xlabel("Episode")
    plt.ylabel("Reward")
    plt.legend()
    plt.show()


def plot_loss(losses):

    plt.figure()
    plt.plot(losses)
    plt.title("DQN Loss Evolution")
    plt.xlabel("Episode")
    plt.ylabel("Loss")
    plt.show()

def plot_slip_error(errors):

    plt.figure()
    plt.plot(errors)
    plt.title("Slip Tracking Error (Deviation from optimal 0.2)")
    plt.xlabel("Episode")
    plt.ylabel("Slip Error")
    plt.show()

def plot_stability(rewards, window=20):

    rewards = np.array(rewards)

    rolling_std = [
        np.std(rewards[max(0, i-window):i+1])
        for i in range(len(rewards))
    ]

    plt.figure(figsize=(8,5))
    plt.plot(rolling_std)

    plt.title("Training Stability (Reward Variance)")
    plt.xlabel("Episode")
    plt.ylabel("Std Dev Reward")
    plt.grid()
    plt.show()

def no_abs_policy(s):
    return 2

def abs_rule_policy(s):

    slip = s[1]  # wheel slip approx

    if slip > 0.25:
        return 0
    elif slip < 0.10:
        return 2
    else:
        return 1

def dqn_policy(agent):

    def policy(s):
        return agent.act(s)

    return policy

def simulate(env, policy, steps=300):

    s, _ = env.reset()

    v_history = []

    for _ in range(steps):

        a = policy(s)

        s, r, terminated, truncated, info = env.step(a)
        done = terminated or truncated

        v_history.append(env.v)

        if done:
            break

    return v_history

def heuristic_abs_policy(s):
    slip = s[1]

    if slip > 0.25:
        return 2
    else:
        return 1

def plot_comparison(env, agent):

    v_red = simulate(env, no_abs_policy)
    v_blue = simulate(env, heuristic_abs_policy)
    v_green = simulate(env, dqn_policy(agent))

    plt.figure(figsize=(10,5))

    plt.plot(v_red, label="Sans ABS", color="red")
    plt.plot(v_blue, label="ABS heuristique", color="blue")
    plt.plot(v_green, label="DQN agent", color="green")

    plt.title("Comparaison des stratégies de freinage")
    plt.xlabel("Steps")
    plt.ylabel("Vitesse véhicule")
    plt.legend()
    plt.grid()
    plt.show()

plot_rewards(rewards)
plot_loss(losses)
plot_slip_error(slip_errors)
plot_comparison(env, agent)